server:
  port: ${PORT}

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/titiscms/ead-config-server-repo
          default-label: master
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PASSWORD}

ead:
  configServer:
    username: ${CONFIG_SERVER_USERNAME}
    password: ${CONFIG_SERVER_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    hostname: ${APP_DOMAIN_NAME}
    non-secure-port: 80

encrypt:
  key-store:
    location: classpath:/config-server.jks
    secret: ${KEYSTORE_SECRET}
    alias: config-server-key
    password: ${KEYSTORE_PASSWORD}